webtalk_init -webtalk_dir F:/ECE410_Lab/Lab2/part2/vending_machine/vending_machine.sim/sim_1/behav/xsim/xsim.dir/vending_m_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Tue Nov  2 04:37:26 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "3746b831-d816-4274-8a28-b1d874c30b12" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "e97c7fab9f5541f5bdbd5087edb14e94" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "84" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1800 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "4" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6272_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3005296309 -regid "" -xml F:/ECE410_Lab/Lab2/part2/vending_machine/vending_machine.sim/sim_1/behav/xsim/xsim.dir/vending_m_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/ECE410_Lab/Lab2/part2/vending_machine/vending_machine.sim/sim_1/behav/xsim/xsim.dir/vending_m_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/ECE410_Lab/Lab2/part2/vending_machine/vending_machine.sim/sim_1/behav/xsim/xsim.dir/vending_m_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
